### ISSUE TITLE
Only 20 projects are available for download

### ISSUE THREAD

**Issue by jsobiecki** [StephenOTT/GitLab-Time-Tracking#20]
After authorisation at gitlab time tracking app, I see, that only part of projects are visible in dropdown widget (up to 20). I don't see if it's documented in Gitlab API wrapper here: http://www.rubydoc.info/gems/gitlab/3.4.0/Gitlab/Client/Projects#projects-instance_method, but changing per_page parameter option solved the issue.

**Comment by StephenOTT** [comment]
Accepted the PR
