### ISSUE TITLE
Wrong data on project details

### ISSUE THREAD

**Issue by jsobiecki** [StephenOTT/GitLab-Time-Tracking#22]
Due the bug in get_project_snapshot_info method, download link and project info were from first downloaded project. 

I fixed mongodb query, and this fixed this issue.

**Comment by StephenOTT** [comment]
@harijari is this: https://github.com/StephenOTT/GitLab-Time-Tracking/pull/23  ?

If yes, can you explain what the bug was?

**Comment by jsobiecki** [comment]
get_project_snaphot_info function created wrong (independent from downloadID argument) query to mongodb. 

This mongodb operator that was missing

```
          { "$match" => {download_id: downloadID}},
```

And because of it, query returned all projects, and took only first from this set. If you have few downloads from different project, this can be reproduced by visiting snapshot link and checking project info or xls file.

**Comment by StephenOTT** [comment]
:+1:

**Comment by StephenOTT** [comment]
PR was merged: https://github.com/StephenOTT/GitLab-Time-Tracking/pull/23
